language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
cache:
  directories:
    - "node_modules"
script:
  - npm run test-cov
after_script:
  - |
    # Upload coverage to coveralls, if exists
    if [[ -f ./coverage/lcov.info ]]; then
      npm install --save-dev coveralls@2
      coveralls < ./coverage/lcov.info
    fi
notifications:
    slack: g-explorer:81CbfYw9kEml7k1QcXQkGfrB
