language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "4.9"
  - "5.12"
  - "6.16"
  - "7.10"
  - "8.15"
  - "9.11"
  - "10.15"
cache:
  directories:
    - "node_modules"
script:
  - npm test
notifications:
    slack: g-explorer:81CbfYw9kEml7k1QcXQkGfrB
