language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
cache:
  directories:
    - "node_modules"
before_install:
  # Configure npm
  - |
    # Skip updating shrinkwrap / lock
    npm config set shrinkwrap false
  # Setup Node.js version-specific dependencies
  - |
    # ava and nyc for testing
    # - remove on Node.js < 6
    if [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -lt 6 ]]; then
      npm rm --save-dev ava
      npm rm --save-dev nyc
    fi
  # Update Node.js modules
  - |
    # Prune & rebuild node_modules
    if [[ -d node_modules ]]; then
      npm prune
      npm rebuild
    fi
script:
  - |
    # Run test script, depending on istanbul install
    if [[ -n "$(npm -ps ls ava nyc)" ]]; then
      npm run test-cov
    else
      exit 0
    fi
after_script:
  - |
    # Upload coverage to coveralls, if exists
    if [[ -f ./coverage/lcov.info ]]; then
      npm install --save-dev coveralls@2
      coveralls < ./coverage/lcov.info
    fi
notifications:
    slack: g-explorer:81CbfYw9kEml7k1QcXQkGfrB
