name: CI

on:
  pull_request:
  push:
    branches:
      - alpha
      - beta
      - master
      - renovate/**

jobs:
  prepare_jobs:
    name: 'Prepare: job optimization'
    runs-on: ubuntu-latest
    outputs:
      pr_found: ${{ steps.pr.outputs.pr_found }}
    steps:
      - name: Get current PR
        id: pr
        uses: 8BitJonny/gh-get-current-pr@2.2.0
        with:
          filterOutClosed: true
          sha: ${{ github.event.pull_request.head.sha }}
  release_semantic_dry:
    needs: prepare_jobs
    name: Release (semantic, dry)
    uses: dargmuesli/github-actions/.github/workflows/release-semantic-next.yml@0.40.17
    if: needs.prepare_jobs.outputs.pr_found == 'false' || github.event_name == 'pull_request'
    permissions:
      contents: write
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    with:
      DRY_RUN: true
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2
  release_semantic:
    needs: build
    name: Release (semantic)
    uses: dargmuesli/github-actions/.github/workflows/release-semantic-next.yml@0.40.17
    permissions:
      contents: write
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}